### ISSUE TITLE
Technical Guideline -- Technical Infrastructure  Update (1)

### ISSUE THREAD

**Issue by Joshocan** [cessda/cessda.guidelines.public#105]
The following require updates:

- [x] Technical Infrastructure Overview subsection: Content rewording 
- [x] GCP Main project Structure subsection: content and diagrams are out of date 
- [x] Technical Infrastructure Detail subsection: Content and diagrams require update 
- [x] Deployment Core Products to Production: Content is out of date 
- [x] Jenkinsfile Template: Update template 
- [x] Jenkins Template for JDK 11: update template 
- [x] Service Configuration : Add to "Service Operation" section

**Comment by matthew-morris-cessda** [comment]
The "Technical Infrastructure Detail" subsection has been renamed to "Repository Types"

**Comment by matthew-morris-cessda** [comment]
All sections updated
