### ISSUE TITLE
Technical Guideline -- Online Forms

### ISSUE THREAD

**Issue by Joshocan** [cessda/cessda.guidelines.public#110]
-  Software Maturity Levels: Update content and forms
- Contributor License Agreement: update terminology and update forms
- Repository Request : Update content and forms 
- ELSST Contributor License Agreement: update content and forms 
- CESSDA Vocabulary Registration Agency 

```[tasklist]
### Tasks
```

**Comment by john-shepherdson** [comment]
In which case, the CVS Agency registration form should be with the CVS documentation.
