### ISSUE TITLE
Release version 1.5.0

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.guidelines.public#130]
- [x] [Release checklist](https://docs.google.com/spreadsheets/d/11VOUXPMRMuR6ylOi47i_V4zXrC89I-aLY1ZOX9CK3ew/edit#gid=0)

**Comment by Joshocan** [comment]
@john-shepherdson What is the status of this release? I am about to create a new release for the recent changes in the technical guideline.

**Comment by matthew-morris-cessda** [comment]
This appears to have been released
