### ISSUE TITLE
Add feedback mechanism

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.guidelines.public#131]
Let users create issues in this issue tracker?

**Comment by Joshocan** [comment]
@john-shepherdson I am confused about this issue: do we want a "Send Feedback" form in the technical guideline? Or should users have a chance to create issues in this repository?

**Comment by john-shepherdson** [comment]
Looking at the linked issue (#52) shows that this refers to a 'Send Feedback' tab, as per CDC etc

**Comment by Joshocan** [comment]
Then we won't need to fix this issue. Feedabck form for CDC is already available.

**Comment by john-shepherdson** [comment]
This isn't about CDC, it is about the Technical Guidelines. Issue 51 refers to CDC as an example

**Comment by Joshocan** [comment]
Feedback form for Technical Guideline

**Comment by Joshocan** [comment]
Deploy the new Jekyll documentation theme gem into the Dev instance for testing.
