### ISSUE TITLE
Deploy the guidelines using continuous deployemnt

### ISSUE THREAD

**Issue by matthew-morris-cessda** [cessda/cessda.guidelines.public#148]
CESSDA is investigating using "continuous deployment" processes (see [CD discussion document](https://docs.google.com/document/d/1MfBFbEe3WPlsrhA2WtYA4lHi3JEY3bzn/edit)) to deploy updates to software and streamline the release process. The technical guidelines are an ideal candidate to experiment with. This issue has a number of subtasks:

- [x] #149
- [x] Remove "development" build, run tests on staging
- [x] Update README to mention that the "main" branch reflects what's deployed to https://docs.tech.cessda.eu/

@john-shepherdson @Joshocan - any feedback would be appreciated

**Comment by john-shepherdson** [comment]
Looks fine. Pity we don't deploy these builds to Zenodo, otherwise we could test auto-updates too.

**Comment by matthew-morris-cessda** [comment]
Continuous deployment integrated
