### ISSUE TITLE
Add Jenkins link to development builds

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.guidelines.public#35]
**Original report on BitBucket by Carsten Thiel (GitHub: [schildwaechter](https://github.com/schildwaechter)).**

----------------------------------------

The string replacement for `JENKINSJOB` should be done and used for all builds.

**Comment by john-shepherdson** [comment]
Has this been completed?

**Comment by matthew-morris-cessda** [comment]
This will not be pursued
