### ISSUE TITLE
Add 'Visual style guide' section

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.guidelines.public#45]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

Based on the User Experience Guide [GoogleDoc](https://docs.google.com/document/d/1pzhHBF_T2Izwy8Ss_7QnjOqJ5mTGA7sELyJ0eLtFmjg/edit?usp=sharing)

**Comment by john-shepherdson** [comment]
No longer relevant
