### ISSUE TITLE
Restyle Send Feedback tab

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.guidelines.public#52]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

‌

```
<script type="text/javascript" src="https://cessda.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-T/sb53l8/b/24/bc54840da492f9ca037209037ef0522a/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector.js?locale=en-GB&collectorId=1393a811"></script>

```

‌

**Comment by matthew-morris-cessda** [comment]
The snippet points to the JIRA instance that has been shut down, so a new snippet is needed.

We should consider sending users to this issue tracker, otherwise we will need to refile issues submitted via the feedback form here anyway.

**Comment by john-shepherdson** [comment]
Replaced by #131
