### ISSUE TITLE
Update Home page

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.guidelines.public#53]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

Add descriptions of recently added sections.

Add full stop to ‘The guidelines also define how CESSDA operates services powered by these products’

**Comment by john-shepherdson** [comment]
Added "Changes since previous version" section

**Comment by john-shepherdson** [comment]
Update release date, update changes since last release
