### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.guidelines.public#57]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

**Comment by schildwaechter** [comment]
Remaining "broken" links are to non-public CESSDA repos, thus Bitbucket returns `404`

**Comment by matthew-morris-cessda** [comment]
This blocks #61.

**Comment by matthew-morris-cessda** [comment]
Fixed in https://github.com/cessda/cessda.guidelines.public/commit/6b2479746c0390bd4b61050b338380417b7dbbff
