### ISSUE TITLE
content duplication

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.guidelines.public#59]
**Original report on BitBucket by Carsten Thiel (GitHub: [schildwaechter](https://github.com/schildwaechter)).**

----------------------------------------

these two pages are \(almost\) identical

[https://docs.tech.cessda.eu/platform/logging-overview.html](https://docs.tech.cessda.eu/platform/logging-overview.html)

[https://docs.tech.cessda.eu/observability/logging-overview.html](https://docs.tech.cessda.eu/observability/logging-overview.html)

**Comment by matthew-morris-cessda** [comment]
@Joshocan Has this been resolved?

**Comment by Joshocan** [comment]
@matthew-morris-cessda Yes, it has been moved.
