### ISSUE TITLE
Document the process for issues and pull requests

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.guidelines.public#60]
**Original report on BitBucket by Matthew Morris (GitHub: [matthew-morris-cessda](https://github.com/matthew-morris-cessda)).**

----------------------------------------

CESSDA has workflows that work must be done against issues and merged with pull requests. The processes for this must be documented.

**Comment by schildwaechter** [comment]
Commit a4332e9 is claiming to relate to this ticket, but the relation is not clear.

**Comment by matthew-morris-cessda** [comment]
I think that was a tempoary workaround to get the build to pass with the broken links in place.

**Comment by matthew-morris-cessda** [comment]
Merged as of 0e7c5b37b47464941a8dc4fd28b117cb184f81f0.
