### ISSUE TITLE
External Link Checking should not be disabled

### ISSUE THREAD

**Issue by schildwaechter** [cessda/cessda.guidelines.public#61]
checking of external links was disabled in a4332e9 without any explanation (except for an obscure reference to reference to the need for documenting pull requests)

**Comment by schildwaechter** [comment]
This relates to #57

**Comment by john-shepherdson** [comment]
Valid external links were being repeatedly marked as broken by the link checker, which was failing the build and hence blocking the release.

**Comment by john-shepherdson** [comment]
* At ./_site/platform/creating-test-suite.html:1:
External link https://bitbucket.org/cessda/cessda.mgmt.selenium/src/master/ failed (status code 404)

* At ./_site/platform/creating-test-suite.html:1:
External link https://bitbucket.org/cessda/cessda.mgmt.sonar/src/master/ failed (status code 404)

* At ./_site/platform/creating-test-suite.html:1:
External link https://bitbucket.org/cessda/cessda.mgmt.jmeter/src/master/ failed (status code 404)

* At ./_site/platform/platform-team-responsibilities.html:1:
External link https://bitbucket.org/cessda/cessda.cdc.userguide/src/master/ failed (status code 404)

* At ./_site/platform/platform-team-responsibilities.html:1:
External link https://bitbucket.org/cessda/cessda.cdc.test/src/master/ failed (status code 404)

* At ./_site/platform/platform-team-responsibilities.html:1:
External link https://bitbucket.org/cessda/cessda.cdc.deploy/src/master/ failed (status code 404)

* At ./_site/platform/platform-team-responsibilities.html:1:
External link https://bitbucket.org/cessda/cessda.cdc.reverse/src/master/ failed (status code 404)

* At ./_site/software/publication.html:2:
External link https://guides.github.com/activities/citable-code/ failed (status code 403)

**Comment by schildwaechter** [comment]
The final one is fixed in #57
