### ISSUE TITLE
Restructure the CESSDA Technical Guidlines

### ISSUE THREAD

**Issue by matthew-morris-cessda** [cessda/cessda.guidelines.public#70]
# Agreed changes to structure

- (000) Home

- (100) Software Development
  - (110) Software Requirements
  - [x] #71
  - (130) Quality Gate
  - (140) Software Releases
    - [x] (1041) Software Publication -> renumber
  - (150) Issue Tracking Workflow
  - (160) Code Archiving
  -   (170) Logging Guidelines
  - [x] #72
    - (1801) End User documentation
    - (1802) Operational documentation
    - (1803) Development documentation
    - [x] (1804) Merging and pull requests -> move up 1 level
    - (1804) Documentation content guidelines -> no need to renumber

- (200) Service Operation
  - (210) Service Requirements
  - (220) Service Objectives --> replace content with link to generic SLA (when published)

- [x] #78
  - [x] (301) Documentation Tooling -> move to ‘Documentation Guidelines’ section
  - [x] (305) Naming Conventions -> move to after Technical Infrastructure Overview
  - (310) Technical Architecture
    - [x]  (3101) Common Interoperability Characteristics <- merge to Infrastructure Compatibility content. Delete
    - [x]  (3102) Future Work (not published) -> delete
    - [x] (3103) Enhancing the Technical Architecture (not published)  -> delete
  - (315) Technical Infrastructure Overview -> Move to top of section
  - (320) GCP Main Project Structure
  - **NEW SECTION** 'Continuous Integration and Deployment’
    - (325) Deployment Pipeline Overview
    - (330) Deployment Workflow
    - (335) Deployment Pipeline Details
    - (336) The CESSDA Branching Model for Deployments
    - (345) Using Helm to deploy products
    - [x] (350) Technical Infrastructure Details -> move up a level (not part of CID)
    - (355) Building Maven Projects with Jenkins
    - (360) Building Docker Images on Jenkins
      - (3601) Adding the Build Jenkinsfile
      - (3602) Adding the Deployment Jenkinsfile
    - (365) Building with Docker
    - (370) Platform Team Responsibilities -> rename to ‘Platform Processes’
      - (3701) Create a Bitbucket Repository -> update for GitHub
      - (3702) Standard Git Repository Contents
      - (3703) Create a New Jenkins Job
      - (3704) Creating a Test Suite
  - [x] (375) Updating CI Tools -> move to platform processes
  - [x] #75
  - [x] (385) Jenkinsfile Template for JDK11 Maven Projects -> update contents
  - **NEW SECTION** ‘Service Configuration’
    - (390) Setup and Configure oauth2-proxy
    - (391) Rate limiting with HAProxy
    - (392) Authenticating with EduTeams

- (400) Software Maturity Levels
  - (410) CA1: Documentation
  - (415) CA2: Intellectual Property
  - (420) CA3: Extensibility
  - (425) CA4: Modularity
  - (430) CA5: Packaging
  - (435) CA6: Portability
  - (440) CA7: Standards Compliance
  - (445) CA8: Maintenance
  - (450) CA9: Verification and Testing
  - (455) CA10: Security
  - (460) CA11: Internationalisation and Localisation
  - (465) CA12: Authentication and Authorisation
  - (492) References
  - [x] (493) Version History (not published) -> delete
  - [x] (494) Document Details/Title Page (not published) -> delete

- [x] #85
  - (510) Monitoring Overview
  - (520) Logging Overview

- (600) Online forms
  - [x] (610) Contributor license agreement -> correct spelling license/licence
  - (620) Repository request
  - (630) Software Maturity Levels
  - [x] (640) ELSST contributor license agreement -> correct spelling license/licence

-(700) Metadata Handling in CESSDA
  - [x] #89
  - [x] #87
  - (730) URN Handling and Resolution
  - (740) Versioning for CVS and ELSST

- (998) Glossary

See [restructuring the CESSDA Technical Guidelines](https://docs.google.com/document/d/18Y34lYqxzTwmV4kEK35shuPcH1VQmFBPhySpm0Y-RSI/edit#) for more details.

**Comment by matthew-morris-cessda** [comment]
@john-shepherdson Could you verify that this is correct?

**Comment by john-shepherdson** [comment]
Correct in what sense? 
1) Is this the new structure that we agreed at the meeting last week? This is my recollection, but I invited you and Joshua to confirm

OR

2) Are all the items to be modified denoted with a checkbox and comment? No.
- (220) Service Objectives needs a checkbox
-  (300) Technical Infrastructure does not need a checkbox, it stays the same but some of its children will be modified
- (315) Technical Infrastructure Overview needs a checkbox
- NEW SECTION 'Continuous Integration and Deployment’ needs a checkbox, as do 325 to 365
- NEW SECTION ‘Service Configuration’ needs a checkbox, as do 390 to 392
- (510) Monitoring Overview needs a checkbox
- (520) Logging Overview needs a checkbox

**Comment by matthew-morris-cessda** [comment]
The first option.

**Comment by john-shepherdson** [comment]
Like I said, that is what I think we agreed. If you and Joshua have looked at the linked Google Doc and do not have any changes to propose, then we can go ahead on that basis.

**Comment by Joshocan** [comment]
Yes, those are all that we agreed on. I think we are ready to go now.

**Comment by matthew-morris-cessda** [comment]
Carsten has made some comments on tech doc restructuring:
Do not remove (710) CESSDA OAI-PMH Identifiers Specification
Do not change (720) Adding a new endpoint
Make (385) Jenkinsfile Template for JDK11 Maven Projects a child of (380) Jenkinsfile Template
   i.e. (3805) Jenkinsfile Template for JDK11 Maven Projects

**Comment by matthew-morris-cessda** [comment]
All tasks done, closing this issue
